* Do the saturation in a good way
We should adjoin the necessary roots of unity
* Test the functions properly

* Ideas for Bernd
** Using Cellular decompositions
The problem in the Mail can be solved by seing that his ideal goes to
zero in the subring with only the cell variables. We should also Mail
this to Ezra.
** Conjecture 5.3
Can we determine the cellular decomposition by hand ?

--- Old Sage Stuff ---
* Classes
** Class :Integer Lattice
   Representation of an Integer Lattice as a matrix of vectors
   generating it. 
*** Methods:
**** Saturate() 
     Gives the generators of the saturated lattice, ie. the lattice of
     all integer points in the linear space spanned by the generators.

     Naive algorithm: Compute the orthogonal complement of the
     generators and take the cycles of this matrix. (Does this work
     over characteristic p>0 ?)

** Class: Partial Character
   Represents a partial character over a field K. Contains an integer
   lattice 
   
   Can we just inheret Integer Lattice ?
*** Data:
**** A Lattice
**** A list of non-zero field elements for each generator
* Notes on the Documentation at [[http://www.sagemath.org/doc/prog/node3.html][sagemath-manual]]
** Find out what Cython and Pyrex are about
** Namings
   Directory Names may be plural, filenames singular. Non-captial
   letters and underscores are standard. No CamelCase
** Every function must have docstring and pass automatic testing: 
   with INPUT, OUTPUT, EXAMPLES, ALGORITHM, AUTHOR,.. 
   see [[http://www.sagemath.org/doc/prog/node9.html][here]] for details
* Observations from other derived classes like [[http://sage.math.washington.edu/home/mhansen/sage-epydoc/sage.rings.polynomial.pbori.BooleanPolynomialIdeal-class.html][BooleanPolynomialIdeal]]
** Why the "coerce" argument ?
** Should we always use the decorator "cached_method"
** Which methods need to be definitely specialized ?
* Mathematical Structure
** Lattice Ideals 
   are completely specified by their partial characters. All
   operations can be run by using only integer lattice operations
** Cellular Ideals
   are generations of lattice ideals. Idea: Looks like a lattice ideal
   in some subset of the variable. 
   Are characterized via variables being either zerodivisors or
   nilpotent. 
** General Binomial Ideals
   Any Binomial Ideal is the intersection of Cellular Binomial Ideals.
   (Algorithm 2 in Ojeda/Sanchez)
   
