* Classes
** Class :Integer Lattice
   Representation of an Integer Lattice as a matrix of vectors
   generating it. 
*** Methods:
**** Saturate() 
     Gives the generators of the saturated lattice, ie. the lattice of
     all integer points in the linear space spanned by the generators.

     Naive algorithm: Compute the orthogonal complement of the
     generators and take the cycles of this matrix. (Does this work
     over characteristic p>0 ?)

** Class: Partial Character
   Represents a partial character over a field K. Contains an integer
   lattice 
   
   Can we just inheret Integer Lattice ?
*** Data:
**** A Lattice
**** A list of non-zero field elements for each generator
* Notes on the Documentation at [[http://www.sagemath.org/doc/prog/node3.html][sagemath-manual]]
** Find out what Cython and Pyrex are about
** Namings
   Directory Names may be plural, filenames singular. Non-captial
   letters and underscores are standard. No CamelCase
** Every function must have docstring and pass automatic testing: 
   with INPUT, OUTPUT, EXAMPLES, ALGORITHM, AUTHOR,.. 
   see [[http://www.sagemath.org/doc/prog/node9.html][here]] for details
* Observations from other derived classes like [[http://sage.math.washington.edu/home/mhansen/sage-epydoc/sage.rings.polynomial.pbori.BooleanPolynomialIdeal-class.html][BooleanPolynomialIdeal]]
  
